language: node_js
node_js:
- '5.7'
cache:
  directories:
  - node_modules
notifications:
  slack:
    secure: VJbwKfOJE2DEx18rR+9VzYVG6EaXfV+vTt2nSU0xMmGJ5bTIJG4yGrTuk9ogTMn6FMBzr7NO2vGsOMp29CGbyShCv7Q5VPwp3HMlrl63uYIidmi/q+RmZtIiu0b8oT2UoUzHq5lp1c0Zd0/wYc8pKqlKYfmLFozrqdAWItygxa3N7WU+DVErbK7ief8W9LbTDDHSuQqHajzhwgLiog9ey8qRI9a6W/i/IW4QqLHDCq25rjisShQ6chyG/w2faolQMdUFWrhzspiNxTkPXYUsr/cFqeF9LdhFmDaj8MVz9ulgLmPUR8CsuCKLkfJVDDep3iI1PZBhmmPOBppsNGtkIM4XvYt9e1dj442YyLNJOPbrAXSAx62fDUHE9v2qGoV58oopyz4gVGdlvdoCqaNtRVoKQ+Ag209TcaGmp9JbJogTfC8TXFaQxf7qLGLKnrRNoEOuGJFfvKKaxRGavDFFAy1vKFP7v5yqaDTaFT0tWBY02fCPhc6p2jjoSmObkrxCjTwM1+tZsD4zpjOE17fthH3b1+Mar2N8rqHWNCcfFNHIAl7RgurRJN9AJm+M+G98YxCzU8qIlkfCvB3G0OQfVnQ1ZQQa7pq30XAGCeBYSTcZxVnbiKftcI9PEPpfGzPR1j9Bxx+nweXMdszi53/kRlj7hC0bSmvD+VM1xKA58qY=
